[workspace]
resolver = "2"
members = [
  "classifier",
  "core",
  "detector",
  "ensemble",
  "examples/*",
  "speciesnet",
  "speciesnet-cli"
]

[workspace.dependencies]
csv = "1"
image = "0.25"
ndarray = "0.17"
num_cpus = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tracing = "0.1"
