[package]
name = "RustTensorflow"
version = "0.1.0"
edition = "2024"

[lib]
name = "speciesnet_rust"
path = "src/lib.rs"

[dependencies]
tensorflow = "0.21"
image = "0.24"
thiserror = "1"
serde_json = "1.0"