[package]
name = "speciesnet-classifier"
version = "0.1.0"
edition = "2024"

[lib]
name = "speciesnet_classifier"
path = "src/lib.rs"

[dependencies]
tensorflow = "0.21"
image = "0.24"
thiserror = "2.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
csv = "1"
