[package]
name = "speciesnet-core"
version = "0.0.3" # Please bump this when doing a release.
authors = [
  "Bhattarapong Somwong <art@zubalis.com>",
  "Antony Harfield <antony@zubalis.com>",
  "Wasuphon Naksut <frongs@zubalis.com>",
]
description = "Core types and traits for speciesnet."
repository = "https://github.com/zubalis/speciesnet-rust"
homepage = "https://github.com/zubalis/speciesnet-rust"
license = "APACHE"
edition = "2024"

[dependencies]
image = { workspace = true }
mozjpeg = "0.10"
ndarray = { workspace = true }
nom = "8"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { version = "1.17", features = ["v4"] }
