[package]
name = "speciesnet-core"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tch = "0.19"
thiserror = "2"
