[package]
name = "speciesnet-core"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25"
mozjpeg = "0.10"
ndarray = "0.16"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.16", features = ["v4"] }
serde_json = "1.0"
thiserror = "2"
