[package]
name = "speciesnet"
version = "0.1.0"
edition = "2024"

[dependencies]
speciesnet-core = { path = "../core" }
speciesnet-detector = { path = "../detector" }
speciesnet-detector-ort = { path = "../detector-ort" }
speciesnet-classifier = { path = "../classifier" }
rayon = "1"
thiserror = "2"
tracing = "0.1"
num_cpus = "1"
