[package]
name = "speciesnet"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
speciesnet-core = { path = "../core" }
speciesnet-detector = { path = "../detector" }
rayon = "1"
thiserror = "2"
clap = { version = "4.5.32", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
walkdir = "2.5.0"
