[package]
name = "speciesnet"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
speciesnet-core = { path = "../core" }
speciesnet-detector = { path = "../detector" }
speciesnet-classifier = { path = "../classifier" }
rayon = "1"
thiserror = "2"
num_cpus = "1.16.0"
