[package]
name = "speciesnet"
version = "0.0.2" # Please bump this when doing a release
authors = [
  "Bhattarapong Somwong <art@zubalis.com>",
  "Antony Harfield <antony@zubalis.com>",
  "Wasuphon Naksut <frongs@zubalis.com>",
]
description = "Home of the ported google's cameratrapai for Rust."
repository = "https://github.com/zubalis/speciesnet-rust"
homepage = "https://github.com/zubalis/speciesnet-rust"
license = "APACHE"
edition = "2024"
readme = "../README.md"

[features]
default = ["download-model"]
download-model = ["dep:serde", "dep:serde_json", "dep:ureq", "dep:directories", "dep:zip"]

[dependencies]
directories = { version = "6", optional = true }
image = { workspace = true }
num_cpus = { workspace = true }
rayon = "1"
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
speciesnet-core = { path = "../core" }
speciesnet-detector = { path = "../detector" }
speciesnet-classifier = { path = "../classifier" }
speciesnet-ensemble = { path = "../ensemble" }
thiserror = { workspace = true }
tracing = { workspace = true }
ureq = { version = "3", optional = true }
zip = { version = "4.0", optional = true }
