[package]
name = "speciesnet-detector-ort"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25"
ndarray = "0.16"
num_cpus = "1"
ort = { version = "=2.0.0-rc.9", features = ["ndarray"] }
speciesnet-core = { path = "../core" }
thiserror = "2.0"
tracing = "0.1"
