[package]
name = "image_load"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
image = "0.25"
## turbojpeg = {version = "1.3.2", features = ["image"]}
zune-jpeg = "0.4.14"
mozjpeg = "0.10.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"