[package]
name = "speciesnet-detector"
version = "0.0.3" # Please bump this when doing a release.
authors = [
  "Bhattarapong Somwong <art@zubalis.com>",
  "Antony Harfield <antony@zubalis.com>",
  "Wasuphon Naksut <frongs@zubalis.com>",
]
description = "Detector components of speciesnet"
repository = "https://github.com/zubalis/speciesnet-rust"
homepage = "https://github.com/zubalis/speciesnet-rust"
license = "APACHE"
edition = "2024"

[dependencies]
image = { workspace = true }
ndarray = { workspace = true }
num_cpus = { workspace = true } 
ort = { version = "=2.0.0-rc.9", default-features = false, features = ["ndarray", "copy-dylibs"] }
ort-sys = "=2.0.0-rc.10"
speciesnet-core = { path = "../core" }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
coreml = ["ort/coreml"]
cuda = ["ort/cuda"]
