name: 'Release'
  
# Run a release on a tag in format `speciesnet-*-x.y.z`.
on:
  push:
    branch:
      - main
    # tags:
    #   - "speciesnet*-[0-9]+.[0-9]+.[0-9]+"

jobs:
  release-docs:
    name: Build documentation
    uses: ./.github/workflows/documentation.yaml
